language: node_js
node_js:
  - "10"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0

script:
  - curl -o .env https://raw.githubusercontent.com/remedcu/Bounty-dApp/dev/.travis.yml
  - ganache-cli &
  - sleep 5
  - truffle test --network development
