language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

before_script:
  - curl -o .env https://raw.githubusercontent.com/remedcu/Bounty-dApp/dev/.dotenv
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0
  - bash startGanache.sh

script:
  - truffle test
  - truffle migrate
  - webpack-cli --mode development

after_script:
  - bash stopGanache.sh

deploy:
  provider: heroku
  email: "admin@remedcu.com"
  api_key:
    secure: $HEROKU_API_KEY
  app: "bountydapp"
  skip_cleanup: true
  on:
    branch: dev